import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Archive, CheckCircle2, FileClock, FileUp, FolderCheck, Loader2, LockKeyhole, Plus, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

const readFile = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });

export default function Sources() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const isAdmin = user?.role === "admin";
  const sources = trpc.knowledge.sources.list.useQuery();
  const documents = trpc.knowledge.documents.list.useQuery();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [classification, setClassification] = useState<"internal" | "confidential" | "restricted">("internal"); const [accessLevel, setAccessLevel] = useState<"all_users" | "admins_only">("all_users");
  const [selectedSourceId, setSelectedSourceId] = useState<string>(""); const [title, setTitle] = useState(""); const [file, setFile] = useState<File | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  const refresh = () => { void utils.knowledge.sources.list.invalidate(); void utils.knowledge.documents.list.invalidate(); void utils.knowledge.workspace.invalidate(); };
  const createSource = trpc.knowledge.sources.create.useMutation({ onSuccess: () => { toast.success("Source created as draft. Approve it before users can retrieve from it."); setName(""); setDescription(""); refresh(); }, onError: error => toast.error(error.message) });
  const approval = trpc.knowledge.sources.setApproval.useMutation({ onSuccess: () => { toast.success("Source status updated."); refresh(); }, onError: error => toast.error(error.message) });
  const upload = trpc.knowledge.documents.upload.useMutation({ onSuccess: result => { result.status === "ready" ? toast.success(`${result.chunkCount} searchable passages are ready.`) : toast.error(result.errorMessage ?? "Document ingestion needs review."); setFile(null); setTitle(""); if (inputRef.current) inputRef.current.value = ""; refresh(); }, onError: error => toast.error(error.message) });
  const submitUpload = async () => { if (!file || !selectedSourceId) return toast.error("Choose both an approved source and a file."); if (file.size > 12 * 1024 * 1024) return toast.error("Files must be 12 MB or smaller."); try { upload.mutate({ sourceId: Number(selectedSourceId), title: title.trim() || file.name.replace(/\.[^.]+$/, ""), filename: file.name, mimeType: file.type || "application/octet-stream", base64: await readFile(file), metadata: { tags: [] } }); } catch { toast.error("The file could not be read."); } };
  const approvedSources = sources.data?.filter(source => source.approvalStatus === "approved") ?? [];
  return <div className="mx-auto max-w-[1240px] space-y-6"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Knowledge governance</p><h1 className="mt-1 font-serif text-3xl tracking-tight text-[#213b2d]">Approved sources</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6b7e70]">Only documents held in an approved source can be retrieved by the agent. Uploads remain in secure storage; the workspace keeps only their metadata and searchable passages.</p></div><Badge className="w-fit border-[#cae2d1] bg-[#eaf6ed] px-3 py-1.5 text-[10px] font-semibold text-[#326d4a]"><LockKeyhole className="mr-1.5 size-3" />{isAdmin ? "Administrator controls enabled" : "Approved sources only"}</Badge></section>
    {isAdmin ? <div className="grid gap-5 lg:grid-cols-2"><Card className="rounded-[1.3rem] border-[#dbe5dc] bg-white"><CardContent className="p-5"><div className="flex items-center gap-2"><Plus className="size-4 text-[#3c8b5b]" /><h2 className="font-serif text-xl text-[#2a4134]">Create a source boundary</h2></div><p className="mt-1 text-xs leading-5 text-[#738277]">Each source has a curator, classification, access rule, and explicit approval state.</p><div className="mt-5 grid gap-3"><div><Label>Source name</Label><Input value={name} onChange={event => setName(event.target.value)} placeholder="e.g., Operations handbook" className="mt-1.5 rounded-lg border-[#dce7df]" /></div><div><Label>Purpose and content</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="What trusted material belongs here?" className="mt-1.5 min-h-20 rounded-lg border-[#dce7df]" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Classification</Label><Select value={classification} onValueChange={value => setClassification(value as typeof classification)}><SelectTrigger className="mt-1.5 rounded-lg"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="internal">Internal</SelectItem><SelectItem value="confidential">Confidential</SelectItem><SelectItem value="restricted">Restricted</SelectItem></SelectContent></Select></div><div><Label>Audience</Label><Select value={accessLevel} onValueChange={value => setAccessLevel(value as typeof accessLevel)}><SelectTrigger className="mt-1.5 rounded-lg"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all_users">All signed-in users</SelectItem><SelectItem value="admins_only">Administrators only</SelectItem></SelectContent></Select></div></div><Button onClick={() => createSource.mutate({ name, description, classification, accessLevel })} disabled={!name.trim() || createSource.isPending} className="mt-1 bg-[#17372f] hover:bg-[#0e2a22]">{createSource.isPending ? <Loader2 className="size-4 animate-spin" /> : <FolderCheck className="size-4" />}Create draft source</Button></div></CardContent></Card>
      <Card className="rounded-[1.3rem] border-[#dbe5dc] bg-[#f2f8f3]"><CardContent className="p-5"><div className="flex items-center gap-2"><UploadCloud className="size-4 text-[#3c8b5b]" /><h2 className="font-serif text-xl text-[#2a4134]">Ingest a firm document</h2></div><p className="mt-1 text-xs leading-5 text-[#738277]">Supported: PDF, DOCX, XLS/XLSX, CSV, TXT, Markdown, and JSON. The initial upload limit is 12 MB.</p><div className="mt-5 grid gap-3"><div><Label>Approved source</Label><Select value={selectedSourceId} onValueChange={setSelectedSourceId}><SelectTrigger className="mt-1.5 rounded-lg bg-white"><SelectValue placeholder="Choose an approved source" /></SelectTrigger><SelectContent>{approvedSources.map(source => <SelectItem key={source.id} value={String(source.id)}>{source.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Document title</Label><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Use a clear, searchable title" className="mt-1.5 rounded-lg bg-white" /></div><div><Label>File</Label><Input ref={inputRef} type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.txt,.md,.json" onChange={event => setFile(event.target.files?.[0] ?? null)} className="mt-1.5 rounded-lg bg-white" />{file ? <p className="mt-1.5 text-[11px] text-[#4f715d]">{file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB</p> : null}</div><Button onClick={submitUpload} disabled={!file || !selectedSourceId || upload.isPending} className="mt-1 bg-[#17372f] hover:bg-[#0e2a22]">{upload.isPending ? <Loader2 className="size-4 animate-spin" /> : <FileUp className="size-4" />}Upload and ingest</Button></div></CardContent></Card></div> : <Card className="rounded-[1.3rem] border-[#dbe5dc] bg-[#f7faf7]"><CardContent className="flex gap-3 p-5 text-sm text-[#5d7364]"><LockKeyhole className="mt-0.5 size-4 text-[#4a8a61]" />Source creation, approval, and document uploads are limited to administrators. You can still use sources that are currently approved for your access level.</CardContent></Card>}
    <section className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card className="rounded-[1.3rem] border-[#dbe5dc] bg-white"><CardContent className="p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Source register</p><h2 className="mt-1 font-serif text-xl text-[#2a4134]">Knowledge boundaries</h2></div><span className="text-xs text-[#718277]">{sources.data?.length ?? 0} total</span></div><div className="mt-4 space-y-2.5">{sources.data?.map(source => <article key={source.id} className="rounded-xl border border-[#e1e9e3] p-3.5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#2f4a3a]">{source.name}</p><p className="mt-1 text-[11px] leading-4 text-[#738277]">{source.description || "No source purpose recorded."}</p></div><Badge variant="outline" className={`shrink-0 text-[9px] capitalize ${source.approvalStatus === "approved" ? "border-[#b9ddc4] bg-[#edf8f0] text-[#348154]" : source.approvalStatus === "archived" ? "border-stone-200 bg-stone-50 text-stone-500" : "border-amber-200 bg-amber-50 text-amber-700"}`}>{source.approvalStatus}</Badge></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] text-[#688073]"><span>{source.classification}</span><span>·</span><span>{source.accessLevel === "all_users" ? "All firm users" : "Administrators only"}</span>{isAdmin && source.approvalStatus !== "archived" ? <div className="ml-auto flex gap-1.5">{source.approvalStatus !== "approved" ? <Button variant="outline" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "approved" })} className="h-7 rounded-lg border-[#c7dfcf] text-[10px] text-[#367a51]"><CheckCircle2 className="mr-1 size-3" />Approve</Button> : <Button variant="ghost" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "draft" })} className="h-7 rounded-lg text-[10px]">Return to draft</Button>}<Button variant="ghost" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "archived" })} className="h-7 rounded-lg text-[10px] text-stone-500"><Archive className="mr-1 size-3" />Archive</Button></div> : null}</div></article>) ?? <p className="py-10 text-center text-sm text-[#7b8b80]">No sources have been created.</p>}</div></CardContent></Card>
      <Card className="rounded-[1.3rem] border-[#dbe5dc] bg-white"><CardContent className="p-5"><div className="flex items-center gap-2"><FileClock className="size-4 text-[#3c8b5b]" /><div><p className="eyebrow">Ingestion register</p><h2 className="mt-1 font-serif text-xl text-[#2a4134]">Document status</h2></div></div><div className="mt-4 space-y-2.5">{documents.data?.map(({ document, sourceName }) => <article key={document.id} className="rounded-xl border border-[#e1e9e3] p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-xs font-semibold text-[#304b3b]">{document.title}</p><p className="mt-1 text-[10px] text-[#768579]">{sourceName} · {(document.byteSize / 1024).toFixed(0)} KB</p></div><Badge variant="outline" className={`text-[9px] ${document.status === "ready" ? "border-[#b9ddc4] bg-[#edf8f0] text-[#348154]" : document.status === "failed" ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-700"}`}>{document.status}</Badge></div><p className="mt-2 text-[10px] leading-4 text-[#718176]">{document.errorMessage || document.extractionSummary || "Awaiting secure processing."}</p></article>) ?? <p className="py-10 text-center text-sm text-[#7b8b80]">No documents have been ingested.</p>}</div></CardContent></Card></section>
  </div>;
}
