import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, Clock3, FilePenLine, Loader2, Send, ShieldAlert, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const statusStyle: Record<string, string> = {
  pending_approval: "border-amber-200 bg-amber-50 text-amber-700",
  approved: "border-emerald-200 bg-emerald-50 text-emerald-700",
  rejected: "border-red-200 bg-red-50 text-red-700",
  cancelled: "border-stone-200 bg-stone-50 text-stone-600",
};

export default function Workflows() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const isAdmin = user?.role === "admin";
  const drafts = trpc.knowledge.workflows.list.useQuery();
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [draftType, setDraftType] = useState<"response" | "summary" | "record_update" | "other">("response"); const [targetSystem, setTargetSystem] = useState("");
  const create = trpc.knowledge.workflows.create.useMutation({ onSuccess: () => { toast.success("Draft is now awaiting human approval."); setTitle(""); setContent(""); setTargetSystem(""); void utils.knowledge.workflows.list.invalidate(); void utils.knowledge.workspace.invalidate(); }, onError: error => toast.error(error.message) });
  const review = trpc.knowledge.workflows.review.useMutation({ onSuccess: result => { toast.success(result.externalActionPerformed ? "Unexpected external action." : "Review decision recorded. No external action was performed."); void utils.knowledge.workflows.list.invalidate(); void utils.knowledge.workspace.invalidate(); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-[1200px] space-y-6"><section className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Controlled workflow</p><h1 className="mt-1 font-serif text-3xl tracking-tight text-[#213b2d]">Drafts under human control</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6b7e70]">This foundation does not send messages, update records, or call external systems. It produces internal drafts only; approval records a decision, never an automated external action.</p></div><Badge className="w-fit border-amber-200 bg-amber-50 px-3 py-1.5 text-[10px] font-semibold text-amber-700"><ShieldAlert className="mr-1.5 size-3" />All outputs are draft-only</Badge></section>
    <div className="grid gap-5 lg:grid-cols-[.86fr_1.14fr]"><Card className="rounded-[1.3rem] border-[#dbe5dc] bg-[#f2f8f3]"><CardContent className="p-5"><div className="flex items-center gap-2"><FilePenLine className="size-4 text-[#3a895a]" /><h2 className="font-serif text-xl text-[#2b4436]">Create an internal draft</h2></div><p className="mt-1 text-xs leading-5 text-[#718076]">Use this for content prepared from a reviewed answer or for an internal work item. It cannot perform an external action.</p><div className="mt-5 space-y-3"><div><Label>Draft title</Label><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Client response draft" className="mt-1.5 rounded-lg bg-white" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Draft type</Label><Select value={draftType} onValueChange={value => setDraftType(value as typeof draftType)}><SelectTrigger className="mt-1.5 rounded-lg bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="response">Response</SelectItem><SelectItem value="summary">Summary</SelectItem><SelectItem value="record_update">Record update proposal</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select></div><div><Label>Future target, optional</Label><Input value={targetSystem} onChange={event => setTargetSystem(event.target.value)} placeholder="e.g., CRM" className="mt-1.5 rounded-lg bg-white" /></div></div><div><Label>Draft content</Label><Textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Write or paste the internal-only draft here…" className="mt-1.5 min-h-44 rounded-lg bg-white" /></div><Button onClick={() => create.mutate({ title, draftType, content, targetSystem: targetSystem || undefined })} disabled={!title.trim() || !content.trim() || create.isPending} className="w-full bg-[#17372f] hover:bg-[#0e2a22]">{create.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}Submit for human review</Button></div></CardContent></Card>
      <Card className="rounded-[1.3rem] border-[#dbe5dc] bg-white"><CardContent className="p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Review queue</p><h2 className="mt-1 font-serif text-xl text-[#2a4134]">{isAdmin ? "All firm drafts" : "Your drafts"}</h2></div><div className="grid size-9 place-items-center rounded-xl bg-[#e8f4eb] text-[#398259]"><Clock3 className="size-4" /></div></div><div className="mt-4 space-y-3">{drafts.data?.map(item => <article key={item.id} className="rounded-xl border border-[#e1e9e3] p-3.5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#304b3b]">{item.title}</p><p className="mt-1 text-[10px] text-[#718176]">{item.draftType.replace("_", " ")}{item.targetSystem ? ` · Future target: ${item.targetSystem}` : " · Internal only"}</p></div><Badge variant="outline" className={`text-[9px] ${statusStyle[item.status]}`}>{item.status.replace("_", " ")}</Badge></div><p className="mt-3 whitespace-pre-wrap rounded-lg bg-[#f8faf8] p-3 text-xs leading-5 text-[#53695b]">{item.content}</p>{item.status === "pending_approval" && isAdmin ? <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => review.mutate({ draftId: item.id, status: "approved", reviewerNote: "Reviewed by administrator. External action remains disabled." })} disabled={review.isPending} className="h-8 flex-1 rounded-lg bg-[#2e7650] text-[11px] hover:bg-[#235b3d]"><Check className="mr-1 size-3" />Approve draft</Button><Button variant="outline" size="sm" onClick={() => review.mutate({ draftId: item.id, status: "rejected", reviewerNote: "Returned for revision." })} disabled={review.isPending} className="h-8 flex-1 rounded-lg border-red-200 text-[11px] text-red-700 hover:bg-red-50"><X className="mr-1 size-3" />Return</Button></div> : null}{item.reviewerNote ? <p className="mt-2 text-[10px] leading-4 text-[#6e8173]"><strong>Review note:</strong> {item.reviewerNote}</p> : null}</article>) ?? <p className="py-12 text-center text-sm text-[#7b8b80]">No drafts have been submitted.</p>}</div></CardContent></Card></div>
  </div>;
}
